export { authConfig } from './config'
export { signToken, verifyToken } from './jwt'
export { authMiddleware } from './middleware'
export { discoverOIDC, resetDiscoveryCache } from './oidc'
export { default as authRoutes } from './routes'
export type { AuthConfig, AuthUser, OIDCDiscoveryDoc, TokenPayload } from './types'
