#!/usr/bin/env bun
/**
 * Compile script: builds the frontend, generates an embedded-asset map,
 * embeds drizzle migrations, then compiles the backend into a single
 * standalone binary.
 *
 * Usage:  bun scripts/compile.ts [--target <bun-target>] [--outfile <name>]
 *
 * Examples:
 *   bun scripts/compile.ts
 *   bun scripts/compile.ts --target bun-linux-x64 --outfile bitk-linux-x64
 *   bun scripts/compile.ts --target bun-darwin-arm64 --outfile bitk-darwin-arm64
 */
import { copyFileSync, readFileSync, unlinkSync } from 'node:fs'
import { resolve } from 'node:path'
import process from 'node:process'
import { parseArgs } from 'node:util'
import { Glob } from 'bun'

const { values: args } = parseArgs({
  options: {
    target: { type: 'string' },
    outfile: { type: 'string' },
    version: { type: 'string' },
    'skip-frontend': { type: 'boolean', default: false },
  },
  strict: false,
})

const ROOT = resolve(import.meta.dir, '..')
const DIST = resolve(ROOT, 'apps/frontend/dist')
const DRIZZLE = resolve(ROOT, 'drizzle')

const STATIC_FILE = resolve(ROOT, 'apps/api/src/static-assets.ts')
const STATIC_BACKUP = resolve(ROOT, 'apps/api/src/static-assets.ts.bak')
const MIGRATIONS_FILE = resolve(ROOT, 'apps/api/src/db/embedded-migrations.ts')
const MIGRATIONS_BACKUP = resolve(ROOT, 'apps/api/src/db/embedded-migrations.ts.bak')

// ---------- 1. Build frontend ----------
if (args['skip-frontend']) {
  console.log('[compile] Skipping frontend build (--skip-frontend)')
} else {
  console.log('[compile] Building frontend...')
  const vite = Bun.spawn(['bun', 'run', 'build'], {
    cwd: ROOT,
    stdio: ['inherit', 'inherit', 'inherit'],
  })
  const viteCode = await vite.exited
  if (viteCode !== 0) {
    console.error('[compile] Frontend build failed')
    process.exit(1)
  }
}

// ---------- 2. Scan dist files ----------
console.log('[compile] Scanning apps/frontend/dist...')
const glob = new Glob('**/*')
const files: string[] = []

for await (const entry of glob.scan({ cwd: DIST, onlyFiles: true })) {
  files.push(entry)
}
files.sort()
console.log(`[compile] Found ${files.length} assets`)

// ---------- 3. Replace static-assets.ts ----------
copyFileSync(STATIC_FILE, STATIC_BACKUP)

const imports: string[] = []
const entries: string[] = []

for (let i = 0; i < files.length; i++) {
  const file = files[i]
  const relPath = `../../frontend/dist/${file}`
  const urlPath = `/${file}`
  imports.push(`import f${i} from ${JSON.stringify(relPath)} with { type: "file" }`)
  entries.push(`  [${JSON.stringify(urlPath)}, f${i}],`)
}

const staticCode = `// Auto-generated by scripts/compile.ts — do not edit
${imports.join('\n')}

export const staticAssets = new Map<string, string>([
${entries.join('\n')}
])
`

await Bun.write(STATIC_FILE, staticCode)
console.log(`[compile] Generated static-assets.ts (${files.length} entries)`)

// ---------- 4. Embed drizzle migrations ----------
console.log('[compile] Embedding drizzle migrations...')
copyFileSync(MIGRATIONS_FILE, MIGRATIONS_BACKUP)

const migrationFiles: string[] = []
const migrationGlob = new Glob('**/*')
for await (const entry of migrationGlob.scan({ cwd: DRIZZLE, onlyFiles: true })) {
  migrationFiles.push(entry)
}
migrationFiles.sort()

const migrationEntries: string[] = []
for (const file of migrationFiles) {
  const content = readFileSync(resolve(DRIZZLE, file), 'utf-8')
  migrationEntries.push(`  [${JSON.stringify(file)}, ${JSON.stringify(content)}],`)
}

const migrationsCode = `// Auto-generated by scripts/compile.ts — do not edit
export const embeddedMigrations = new Map<string, string>([
${migrationEntries.join('\n')}
])
`

await Bun.write(MIGRATIONS_FILE, migrationsCode)
console.log(`[compile] Generated embedded-migrations.ts (${migrationFiles.length} files)`)

// ---------- 5. Compile to single binary ----------
const target = (args.target as string | undefined) ?? null
const outfile = resolve(ROOT, (args.outfile as string | undefined) ?? 'bitk')
console.log(`[compile] Compiling binary...${target ? ` (target: ${target})` : ''}`)
const version = args.version ?? 'dev'
const gitCommit = Bun.spawnSync(['git', 'rev-parse', '--short', 'HEAD'], { cwd: ROOT })
const commit = gitCommit.stdout.toString().trim() || 'unknown'
console.log(`[compile] Version: ${version} (${commit})`)
const compileArgs = [
  'bun',
  'build',
  'apps/api/src/index.ts',
  '--compile',
  '--define',
  `__BITK_VERSION__="${version}"`,
  '--define',
  `__BITK_COMMIT__="${commit}"`,
  '--outfile',
  outfile,
]
if (target) compileArgs.splice(4, 0, '--target', target)
const build = Bun.spawn(compileArgs, {
  cwd: ROOT,
  stdio: ['inherit', 'inherit', 'inherit'],
})
const buildCode = await build.exited

// ---------- 6. Restore stub files ----------
copyFileSync(STATIC_BACKUP, STATIC_FILE)
try {
  unlinkSync(STATIC_BACKUP)
} catch {}

copyFileSync(MIGRATIONS_BACKUP, MIGRATIONS_FILE)
try {
  unlinkSync(MIGRATIONS_BACKUP)
} catch {}

if (buildCode !== 0) {
  console.error('[compile] Binary compilation failed')
  process.exit(1)
}

console.log(`[compile] Done! Binary: ${outfile}`)
const stat = Bun.file(outfile)
console.log(`[compile] Size: ${(stat.size / 1024 / 1024).toFixed(1)} MB`)
